// Location pool for TapMap. Coordinates are decimal degrees (WGS84).
// difficulty: "easy" = world-famous, "medium" = well known, "hard" = remote or obscure.
export const LOCATIONS = [
  // Easy
  { name: "Eiffel Tower, Paris, France", hint: "Iron lattice tower built for the 1889 World's Fair", lat: 48.8584, lng: 2.2945, difficulty: "easy" },
  { name: "Statue of Liberty, New York, USA", hint: "A copper gift from France stands in this harbour", lat: 40.6892, lng: -74.0445, difficulty: "easy" },
  { name: "Great Pyramid of Giza, Egypt", hint: "The last standing wonder of the ancient world", lat: 29.9792, lng: 31.1342, difficulty: "easy" },
  { name: "Sydney Opera House, Australia", hint: "Sail-shaped roofs on a harbour peninsula", lat: -33.8568, lng: 151.2153, difficulty: "easy" },
  { name: "Colosseum, Rome, Italy", hint: "Gladiators once fought in this amphitheatre", lat: 41.8902, lng: 12.4922, difficulty: "easy" },
  { name: "Taj Mahal, Agra, India", hint: "White marble mausoleum on the Yamuna river", lat: 27.1751, lng: 78.0421, difficulty: "easy" },
  { name: "Big Ben, London, UK", hint: "The great bell of the Palace of Westminster", lat: 51.5007, lng: -0.1246, difficulty: "easy" },
  { name: "Christ the Redeemer, Rio de Janeiro, Brazil", hint: "Arms outstretched above Corcovado mountain", lat: -22.9519, lng: -43.2105, difficulty: "easy" },
  { name: "Mount Fuji, Japan", hint: "A snow-capped volcano on Honshu", lat: 35.3606, lng: 138.7274, difficulty: "easy" },
  { name: "Golden Gate Bridge, San Francisco, USA", hint: "\"International orange\" suspension bridge", lat: 37.8199, lng: -122.4783, difficulty: "easy" },
  { name: "Tokyo, Japan", hint: "The world's largest metropolitan area", lat: 35.6762, lng: 139.6503, difficulty: "easy" },
  { name: "Machu Picchu, Peru", hint: "Inca citadel high in the Andes", lat: -13.1631, lng: -72.545, difficulty: "easy" },
  { name: "Great Wall at Badaling, China", hint: "The most visited section, northwest of Beijing", lat: 40.3587, lng: 116.02, difficulty: "easy" },
  { name: "Niagara Falls, Canada/USA", hint: "Three waterfalls on a border river between two Great Lakes", lat: 43.0896, lng: -79.0849, difficulty: "easy" },
  { name: "Grand Canyon, Arizona, USA", hint: "Carved over millions of years by the Colorado River", lat: 36.1069, lng: -112.1129, difficulty: "easy" },
  { name: "Mount Everest, Nepal/China", hint: "Earth's highest summit above sea level", lat: 27.9881, lng: 86.925, difficulty: "easy" },
  { name: "Red Square, Moscow, Russia", hint: "Beside the Kremlin and St Basil's Cathedral", lat: 55.7539, lng: 37.6208, difficulty: "easy" },
  { name: "Cape Town, South Africa", hint: "A city beneath flat-topped Table Mountain", lat: -33.9249, lng: 18.4241, difficulty: "easy" },
  { name: "Burj Khalifa, Dubai, UAE", hint: "The world's tallest building", lat: 25.1972, lng: 55.2744, difficulty: "easy" },
  { name: "Acropolis, Athens, Greece", hint: "The Parthenon crowns this rocky hill", lat: 37.9715, lng: 23.7257, difficulty: "easy" },

  // Medium
  { name: "Petra, Jordan", hint: "The \"Rose City\" carved into sandstone cliffs", lat: 30.3285, lng: 35.4444, difficulty: "medium" },
  { name: "Angkor Wat, Cambodia", hint: "The largest religious monument in the world", lat: 13.4125, lng: 103.867, difficulty: "medium" },
  { name: "Chichén Itzá, Mexico", hint: "Maya step-pyramid on the Yucatán Peninsula", lat: 20.6843, lng: -88.5678, difficulty: "medium" },
  { name: "Uluru, Australia", hint: "A sacred sandstone monolith in the Red Centre", lat: -25.3444, lng: 131.0369, difficulty: "medium" },
  { name: "Victoria Falls, Zambia/Zimbabwe", hint: "\"The smoke that thunders\" on the Zambezi", lat: -17.9243, lng: 25.8572, difficulty: "medium" },
  { name: "Mount Kilimanjaro, Tanzania", hint: "Africa's highest peak, a free-standing volcano", lat: -3.0674, lng: 37.3556, difficulty: "medium" },
  { name: "Iguazu Falls, Argentina/Brazil", hint: "Hundreds of cascades on a triple border", lat: -25.6953, lng: -54.4367, difficulty: "medium" },
  { name: "Reykjavík, Iceland", hint: "The world's northernmost national capital", lat: 64.1466, lng: -21.9426, difficulty: "medium" },
  { name: "Istanbul, Turkey", hint: "A city that straddles Europe and Asia on the Bosphorus", lat: 41.0082, lng: 28.9784, difficulty: "medium" },
  { name: "Buenos Aires, Argentina", hint: "Birthplace of the tango, on the Río de la Plata", lat: -34.6037, lng: -58.3816, difficulty: "medium" },
  { name: "Nairobi, Kenya", hint: "A capital with a national park inside city limits", lat: -1.2921, lng: 36.8219, difficulty: "medium" },
  { name: "Bangkok, Thailand", hint: "Temples and canals along the Chao Phraya river", lat: 13.7563, lng: 100.5018, difficulty: "medium" },
  { name: "Stonehenge, England", hint: "A prehistoric stone circle on Salisbury Plain", lat: 51.1789, lng: -1.8262, difficulty: "medium" },
  { name: "Santorini, Greece", hint: "White-washed villages on a volcanic caldera in the Aegean", lat: 36.3932, lng: 25.4615, difficulty: "medium" },
  { name: "Galápagos Islands, Ecuador", hint: "Darwin's islands, straddling the equator", lat: -0.9538, lng: -90.9656, difficulty: "medium" },
  { name: "Banff, Alberta, Canada", hint: "Turquoise lakes in the Canadian Rockies", lat: 51.1784, lng: -115.5708, difficulty: "medium" },
  { name: "Ha Long Bay, Vietnam", hint: "Thousands of limestone islands in the Gulf of Tonkin", lat: 20.9101, lng: 107.1839, difficulty: "medium" },
  { name: "Serengeti, Tanzania", hint: "Plains of the great wildebeest migration", lat: -2.3333, lng: 34.8333, difficulty: "medium" },
  { name: "Dead Sea, Israel/Jordan", hint: "The lowest land point on Earth, and very salty", lat: 31.559, lng: 35.4732, difficulty: "medium" },
  { name: "Marrakesh, Morocco", hint: "The \"Red City\" at the foot of the Atlas Mountains", lat: 31.6295, lng: -7.9811, difficulty: "medium" },
  { name: "Kyoto, Japan", hint: "Imperial capital for over a thousand years", lat: 35.0116, lng: 135.7681, difficulty: "medium" },
  { name: "Singapore", hint: "A city-state at the tip of the Malay Peninsula", lat: 1.3521, lng: 103.8198, difficulty: "medium" },
  { name: "Honolulu, Hawaii, USA", hint: "Home of Waikiki Beach on the island of Oʻahu", lat: 21.3069, lng: -157.8583, difficulty: "medium" },
  { name: "Anchorage, Alaska, USA", hint: "The largest city in the largest US state", lat: 61.2181, lng: -149.9003, difficulty: "medium" },
  { name: "Great Barrier Reef, Australia", hint: "The world's largest coral reef system, off Queensland", lat: -16.75, lng: 146.0, difficulty: "medium" },
  { name: "Mexico City, Mexico", hint: "Built on the ruins of the Aztec capital Tenochtitlan", lat: 19.4326, lng: -99.1332, difficulty: "medium" },
  { name: "Havana, Cuba", hint: "Classic cars and a seaside promenade called the Malecón", lat: 23.1136, lng: -82.3666, difficulty: "medium" },
  { name: "Auckland, New Zealand", hint: "The \"City of Sails\", built on volcanic fields", lat: -36.8485, lng: 174.7633, difficulty: "medium" },

  // Hard
  { name: "Easter Island, Chile", hint: "Giant carved moai heads on a remote Pacific island", lat: -27.1127, lng: -109.3497, difficulty: "hard" },
  { name: "Suva, Fiji", hint: "A South Pacific capital close to the 180° meridian", lat: -18.1248, lng: 178.4501, difficulty: "hard" },
  { name: "Timbuktu, Mali", hint: "A historic centre of learning at the edge of the Sahara", lat: 16.7666, lng: -3.0026, difficulty: "hard" },
  { name: "Ulaanbaatar, Mongolia", hint: "The coldest national capital on Earth", lat: 47.8864, lng: 106.9057, difficulty: "hard" },
  { name: "Longyearbyen, Svalbard, Norway", hint: "One of the northernmost towns in the world", lat: 78.2232, lng: 15.6267, difficulty: "hard" },
  { name: "Socotra, Yemen", hint: "Island of dragon's blood trees in the Arabian Sea", lat: 12.4634, lng: 53.8237, difficulty: "hard" },
  { name: "Lake Baikal, Russia", hint: "The deepest and oldest freshwater lake", lat: 53.5587, lng: 108.165, difficulty: "hard" },
  { name: "Salar de Uyuni, Bolivia", hint: "The world's largest salt flat", lat: -20.1338, lng: -67.4891, difficulty: "hard" },
  { name: "Bagan, Myanmar", hint: "Thousands of ancient temples on a river plain", lat: 21.1717, lng: 94.8585, difficulty: "hard" },
  { name: "Nuuk, Greenland", hint: "Capital of the world's largest island", lat: 64.1814, lng: -51.6941, difficulty: "hard" },
  { name: "Ushuaia, Argentina", hint: "Often called the southernmost city in the world", lat: -54.8019, lng: -68.303, difficulty: "hard" },
  { name: "Lalibela, Ethiopia", hint: "Churches carved down into solid rock", lat: 12.0317, lng: 39.0473, difficulty: "hard" },
  { name: "Tristan da Cunha", hint: "The most remote inhabited archipelago, in the South Atlantic", lat: -37.1052, lng: -12.2777, difficulty: "hard" },
  { name: "Samarkand, Uzbekistan", hint: "Turquoise domes on the ancient Silk Road", lat: 39.627, lng: 66.975, difficulty: "hard" },
  { name: "McMurdo Station, Antarctica", hint: "The largest research base on the frozen continent", lat: -77.8419, lng: 166.6863, difficulty: "hard" },
  { name: "Sossusvlei, Namibia", hint: "Towering red dunes in the Namib Desert", lat: -24.7275, lng: 15.3428, difficulty: "hard" },
  { name: "Cradle Mountain, Tasmania, Australia", hint: "Jagged peaks above Dove Lake on an island state", lat: -41.6848, lng: 145.951, difficulty: "hard" },
  { name: "Apia, Samoa", hint: "A Pacific capital that skipped a day in 2011", lat: -13.8506, lng: -171.7513, difficulty: "hard" },
  { name: "Nazca Lines, Peru", hint: "Giant geoglyphs best seen from the air", lat: -14.739, lng: -75.13, difficulty: "hard" },
  { name: "Koror, Palau", hint: "Rock islands in the western Pacific", lat: 7.3419, lng: 134.4792, difficulty: "hard" },
];
