// Location pool for TapMap. Coordinates are decimal degrees (WGS84).
// difficulty: "easy" = world-famous, "medium" = well known, "hard" = remote or obscure.
// notes: one line shown when the answer is revealed.
export const LOCATIONS = [
  // Easy
  { name: "Eiffel Tower, Paris, France", lat: 48.8584, lng: 2.2945, difficulty: "easy", notes: "Built for the 1889 World's Fair, it was only meant to stand for 20 years." },
  { name: "Statue of Liberty, New York, USA", lat: 40.6892, lng: -74.0445, difficulty: "easy", notes: "A gift from France, dedicated in 1886. Its copper skin is thinner than 2.5 mm." },
  { name: "Great Pyramid of Giza, Egypt", lat: 29.9792, lng: 31.1342, difficulty: "easy", notes: "It was the tallest human-made structure on Earth for more than 3,800 years." },
  { name: "Sydney Opera House, Australia", lat: -33.8568, lng: 151.2153, difficulty: "easy", notes: "Its roof sails are covered in over a million tiles made in Sweden." },
  { name: "Colosseum, Rome, Italy", lat: 41.8902, lng: 12.4922, difficulty: "easy", notes: "It could seat an estimated 50,000 to 80,000 spectators." },
  { name: "Taj Mahal, Agra, India", lat: 27.1751, lng: 78.0421, difficulty: "easy", notes: "Shah Jahan built it as a tomb for his wife Mumtaz Mahal. Work began in 1632." },
  { name: "Big Ben, London, UK", lat: 51.5007, lng: -0.1246, difficulty: "easy", notes: "Big Ben is the great bell, not the tower, which has been called Elizabeth Tower since 2012." },
  { name: "Christ the Redeemer, Rio de Janeiro, Brazil", lat: -22.9519, lng: -43.2105, difficulty: "easy", notes: "Finished in 1931, the statue is 30 m tall, not counting its pedestal." },
  { name: "Mount Fuji, Japan", lat: 35.3606, lng: 138.7274, difficulty: "easy", notes: "Japan's highest peak, at 3,776 m. It last erupted in 1707." },
  { name: "Golden Gate Bridge, San Francisco, USA", lat: 37.8199, lng: -122.4783, difficulty: "easy", notes: "Its colour, International Orange, was chosen to stand out in the fog." },
  { name: "Tokyo, Japan", lat: 35.6762, lng: 139.6503, difficulty: "easy", notes: "Greater Tokyo is the world's most populous metropolitan area, with about 37 million people." },
  { name: "Machu Picchu, Peru", lat: -13.1631, lng: -72.545, difficulty: "easy", notes: "The Inca built this citadel in the 15th century, about 2,430 m above sea level." },
  { name: "Great Wall at Badaling, China", lat: 40.3587, lng: 116.02, difficulty: "easy", notes: "Badaling is the Great Wall's most visited section, and it opened to tourists in 1957." },
  { name: "Niagara Falls, Canada/USA", lat: 43.0896, lng: -79.0849, difficulty: "easy", notes: "Horseshoe Falls, on the Canadian side, carries about 90% of the river's water." },
  { name: "Grand Canyon, Arizona, USA", lat: 36.1069, lng: -112.1129, difficulty: "easy", notes: "The Colorado River carved it up to 1.8 km deep." },
  { name: "Mount Everest, Nepal/China", lat: 27.9881, lng: 86.925, difficulty: "easy", notes: "At 8,849 m, its summit is the highest point above sea level on Earth." },
  { name: "Red Square, Moscow, Russia", lat: 55.7539, lng: 37.6208, difficulty: "easy", notes: "Its name comes from an old Russian word for \"beautiful\", not from the colour." },
  { name: "Cape Town, South Africa", lat: -33.9249, lng: 18.4241, difficulty: "easy", notes: "The flat-topped Table Mountain rises straight up behind the city." },
  { name: "Burj Khalifa, Dubai, UAE", lat: 25.1972, lng: 55.2744, difficulty: "easy", notes: "At 828 m, it has been the world's tallest building since 2010." },
  { name: "Acropolis, Athens, Greece", lat: 37.9715, lng: 23.7257, difficulty: "easy", notes: "The Parthenon was built on its summit in the 5th century BC." },

  // Medium
  { name: "Petra, Jordan", lat: 30.3285, lng: 35.4444, difficulty: "medium", notes: "The Nabataeans carved the city's façades straight into rose-pink sandstone cliffs." },
  { name: "Angkor Wat, Cambodia", lat: 13.4125, lng: 103.867, difficulty: "medium", notes: "The world's largest religious monument, and it's on Cambodia's flag." },
  { name: "Chichén Itzá, Mexico", lat: 20.6843, lng: -88.5678, difficulty: "medium", notes: "At the equinoxes, shadows make a serpent that seems to slide down El Castillo's steps." },
  { name: "Uluru, Australia", lat: -25.3444, lng: 131.0369, difficulty: "medium", notes: "This sandstone monolith rises about 348 m above the flat desert around it." },
  { name: "Victoria Falls, Zambia/Zimbabwe", lat: -17.9243, lng: 25.8572, difficulty: "medium", notes: "Its local name, Mosi-oa-Tunya, means \"the smoke that thunders\"." },
  { name: "Mount Kilimanjaro, Tanzania", lat: -3.0674, lng: 37.3556, difficulty: "medium", notes: "Africa's highest mountain, at 5,895 m, is a dormant volcano." },
  { name: "Iguazu Falls, Argentina/Brazil", lat: -25.6953, lng: -54.4367, difficulty: "medium", notes: "It is a chain of about 275 waterfalls on the border of Argentina and Brazil." },
  { name: "Reykjavík, Iceland", lat: 64.1466, lng: -21.9426, difficulty: "medium", notes: "It is the world's northernmost capital of a sovereign state." },
  { name: "Istanbul, Turkey", lat: 41.0082, lng: 28.9784, difficulty: "medium", notes: "The city sits on both sides of the Bosphorus, so it is partly in Europe and partly in Asia." },
  { name: "Buenos Aires, Argentina", lat: -34.6037, lng: -58.3816, difficulty: "medium", notes: "Avenida 9 de Julio, one of the widest avenues in the world, runs through the centre." },
  { name: "Nairobi, Kenya", lat: -1.2921, lng: 36.8219, difficulty: "medium", notes: "Nairobi National Park is inside the city, and you can see giraffes against the skyline." },
  { name: "Bangkok, Thailand", lat: 13.7563, lng: 100.5018, difficulty: "medium", notes: "Its full ceremonial name is one of the longest place names in the world." },
  { name: "Stonehenge, England", lat: 51.1789, lng: -1.8262, difficulty: "medium", notes: "Its smaller bluestones were brought from the Preseli Hills in Wales, more than 200 km away." },
  { name: "Santorini, Greece", lat: 36.3932, lng: 25.4615, difficulty: "medium", notes: "The island's crescent is the rim of a caldera left by a huge eruption around 1600 BC." },
  { name: "Galápagos Islands, Ecuador", lat: -0.9538, lng: -90.9656, difficulty: "medium", notes: "Their wildlife helped shape Charles Darwin's thinking after he visited in 1835." },
  { name: "Banff, Alberta, Canada", lat: 51.1784, lng: -115.5708, difficulty: "medium", notes: "Banff, founded in 1885, is Canada's first national park." },
  { name: "Ha Long Bay, Vietnam", lat: 20.9101, lng: 107.1839, difficulty: "medium", notes: "About 1,600 limestone islands and islets rise out of its water." },
  { name: "Serengeti, Tanzania", lat: -2.3333, lng: 34.8333, difficulty: "medium", notes: "It is home to the great migration of more than a million wildebeest." },
  { name: "Dead Sea, Israel/Jordan", lat: 31.559, lng: 35.4732, difficulty: "medium", notes: "Its shore, more than 430 m below sea level, is the lowest land on Earth." },
  { name: "Marrakesh, Morocco", lat: 31.6295, lng: -7.9811, difficulty: "medium", notes: "Every evening its main square, Jemaa el-Fnaa, fills with food stalls and performers." },
  { name: "Kyoto, Japan", lat: 35.0116, lng: 135.7681, difficulty: "medium", notes: "It was Japan's capital for more than a thousand years, until 1869." },
  { name: "Singapore", lat: 1.3521, lng: 103.8198, difficulty: "medium", notes: "This city-state of more than 60 islands lies just north of the equator." },
  { name: "Honolulu, Hawaii, USA", lat: 21.3069, lng: -157.8583, difficulty: "medium", notes: "ʻIolani Palace is here, the only royal palace in the United States." },
  { name: "Anchorage, Alaska, USA", lat: 61.2181, lng: -149.9003, difficulty: "medium", notes: "Alaska's largest city is home to about two in five Alaskans." },
  { name: "Great Barrier Reef, Australia", lat: -16.75, lng: 146.0, difficulty: "medium", notes: "The world's largest coral reef system stretches more than 2,300 km." },
  { name: "Mexico City, Mexico", lat: 19.4326, lng: -99.1332, difficulty: "medium", notes: "It was built on the site of the Aztec capital Tenochtitlan, on a drained lake bed." },
  { name: "Havana, Cuba", lat: 23.1136, lng: -82.3666, difficulty: "medium", notes: "The Spanish founded it in 1519, and its old town is a World Heritage Site." },
  { name: "Auckland, New Zealand", lat: -36.8485, lng: 174.7633, difficulty: "medium", notes: "The city is built on a field of about 50 volcanoes." },

  // Hard
  { name: "Easter Island, Chile", lat: -27.1127, lng: -109.3497, difficulty: "hard", notes: "The Rapa Nui people carved nearly 1,000 moai statues here." },
  { name: "Suva, Fiji", lat: -18.1248, lng: 178.4501, difficulty: "hard", notes: "Fiji's capital is on Viti Levu, the country's largest island." },
  { name: "Timbuktu, Mali", lat: 16.7666, lng: -3.0026, difficulty: "hard", notes: "In the 15th and 16th centuries it was a great centre of Islamic learning." },
  { name: "Ulaanbaatar, Mongolia", lat: 47.8864, lng: 106.9057, difficulty: "hard", notes: "It is often called the coldest capital city in the world." },
  { name: "Longyearbyen, Svalbard, Norway", lat: 78.2232, lng: 15.6267, difficulty: "hard", notes: "The Svalbard Global Seed Vault is here, holding seeds from around the world." },
  { name: "Socotra, Yemen", lat: 12.4634, lng: 53.8237, difficulty: "hard", notes: "The island is known for its umbrella-shaped dragon's blood trees, which grow nowhere else." },
  { name: "Lake Baikal, Russia", lat: 53.5587, lng: 108.165, difficulty: "hard", notes: "The world's deepest lake holds about a fifth of Earth's unfrozen surface fresh water." },
  { name: "Salar de Uyuni, Bolivia", lat: -20.1338, lng: -67.4891, difficulty: "hard", notes: "After rain, the world's largest salt flat becomes a giant mirror." },
  { name: "Bagan, Myanmar", lat: 21.1717, lng: 94.8585, difficulty: "hard", notes: "More than 2,000 Buddhist temples and pagodas still stand on its plain." },
  { name: "Nuuk, Greenland", lat: 64.1814, lng: -51.6941, difficulty: "hard", notes: "Greenland's capital was founded in 1728 and is one of the smallest capitals in the world." },
  { name: "Ushuaia, Argentina", lat: -54.8019, lng: -68.303, difficulty: "hard", notes: "It is often called the southernmost city in the world." },
  { name: "Lalibela, Ethiopia", lat: 12.0317, lng: 39.0473, difficulty: "hard", notes: "Its 11 medieval churches were carved downwards out of solid rock." },
  { name: "Tristan da Cunha", lat: -37.1052, lng: -12.2777, difficulty: "hard", notes: "Fewer than 300 people live on the world's most remote inhabited island group." },
  { name: "Samarkand, Uzbekistan", lat: 39.627, lng: 66.975, difficulty: "hard", notes: "On this Silk Road city's Registan square stand three madrasas covered in tiles." },
  { name: "McMurdo Station, Antarctica", lat: -77.8419, lng: 166.6863, difficulty: "hard", notes: "The United States runs Antarctica's largest research station here." },
  { name: "Sossusvlei, Namibia", lat: -24.7275, lng: 15.3428, difficulty: "hard", notes: "Some of its red dunes are more than 300 m high, among the tallest in the world." },
  { name: "Cradle Mountain, Tasmania, Australia", lat: -41.6848, lng: 145.951, difficulty: "hard", notes: "It is the start of the Overland Track, one of Australia's best-known long walks." },
  { name: "Apia, Samoa", lat: -13.8506, lng: -171.7513, difficulty: "hard", notes: "Samoa is just west of the International Date Line, so it is among the first places to see each new day." },
  { name: "Nazca Lines, Peru", lat: -14.739, lng: -75.13, difficulty: "hard", notes: "These giant figures were scratched into the desert about 2,000 years ago and are best seen from the air." },
  { name: "Koror, Palau", lat: 7.3419, lng: 134.4792, difficulty: "hard", notes: "Palau's largest town was its capital until 2006." },

  // Added 27 September 2026 (in the daily pool from the 28th, like the database rows).
  // Easy
  { name: "Leaning Tower of Pisa, Italy", lat: 43.723, lng: 10.3966, difficulty: "easy", added_on: "2026-09-27", notes: "It started to lean in the 1170s, while it was still being built, because the ground is soft." },
  { name: "Sagrada Família, Barcelona, Spain", lat: 41.4036, lng: 2.1744, difficulty: "easy", added_on: "2026-09-27", notes: "Gaudí's basilica has been under construction since 1882." },
  { name: "Brandenburg Gate, Berlin, Germany", lat: 52.5163, lng: 13.3777, difficulty: "easy", added_on: "2026-09-27", notes: "Built in the 1790s, it stood right by the Berlin Wall from 1961 to 1989." },
  { name: "Chicago, USA", lat: 41.8781, lng: -87.6298, difficulty: "easy", added_on: "2026-09-27", notes: "The world's first skyscraper, the Home Insurance Building, went up here in 1885." },
  { name: "Forbidden City, Beijing, China", lat: 39.9163, lng: 116.3972, difficulty: "easy", added_on: "2026-09-27", notes: "It was the home of China's emperors for almost 500 years." },
  { name: "Hollywood Sign, Los Angeles, USA", lat: 34.1341, lng: -118.3215, difficulty: "easy", added_on: "2026-09-27", notes: "It first read \"Hollywoodland\", an advert for a housing development in 1923." },
  { name: "Mount Rushmore, South Dakota, USA", lat: 43.8791, lng: -103.4591, difficulty: "easy", added_on: "2026-09-27", notes: "Each of the four presidents' faces is about 18 m tall." },
  { name: "Neuschwanstein Castle, Germany", lat: 47.5576, lng: 10.7498, difficulty: "easy", added_on: "2026-09-27", notes: "This 19th-century castle inspired Disney's Sleeping Beauty castle." },
  { name: "Venice, Italy", lat: 45.4408, lng: 12.3155, difficulty: "easy", added_on: "2026-09-27", notes: "The city is built on 118 small islands, linked by more than 400 bridges." },
  { name: "Hong Kong", lat: 22.3193, lng: 114.1694, difficulty: "easy", added_on: "2026-09-27", notes: "It has more skyscrapers than any other city in the world." },
  { name: "Las Vegas Strip, Nevada, USA", lat: 36.1147, lng: -115.1728, difficulty: "easy", added_on: "2026-09-27", notes: "Most of the Strip is actually outside Las Vegas, in the town of Paradise." },
  { name: "Amsterdam, Netherlands", lat: 52.3676, lng: 4.9041, difficulty: "easy", added_on: "2026-09-27", notes: "The city has more than 100 km of canals." },
  { name: "Petronas Towers, Kuala Lumpur, Malaysia", lat: 3.1579, lng: 101.7116, difficulty: "easy", added_on: "2026-09-27", notes: "They were the world's tallest buildings from 1998 to 2004." },
  { name: "CN Tower, Toronto, Canada", lat: 43.6426, lng: -79.3871, difficulty: "easy", added_on: "2026-09-27", notes: "It was the world's tallest free-standing structure for more than 30 years." },
  { name: "Seoul, South Korea", lat: 37.5665, lng: 126.978, difficulty: "easy", added_on: "2026-09-27", notes: "About half of South Korea's people live in the Seoul metropolitan area." },
  { name: "Mont-Saint-Michel, France", lat: 48.6361, lng: -1.5115, difficulty: "easy", added_on: "2026-09-27", notes: "At high tide, the sea can cut this abbey island off from the mainland." },
  // Medium
  { name: "Matterhorn, Switzerland/Italy", lat: 45.9763, lng: 7.6586, difficulty: "medium", added_on: "2026-09-27", notes: "The first ascent, in 1865, ended in tragedy: four of the seven climbers died on the way down." },
  { name: "Cappadocia, Turkey", lat: 38.6431, lng: 34.8289, difficulty: "medium", added_on: "2026-09-27", notes: "People carved homes and churches into its soft rock \"fairy chimneys\"." },
  { name: "Geirangerfjord, Norway", lat: 62.1049, lng: 7.094, difficulty: "medium", added_on: "2026-09-27", notes: "Its waterfalls include the Seven Sisters, which tumble down the fjord's cliffs." },
  { name: "Lake Titicaca, Peru/Bolivia", lat: -15.9254, lng: -69.3354, difficulty: "medium", added_on: "2026-09-27", notes: "At about 3,800 m, it's often called the highest navigable lake in the world." },
  { name: "Yellowstone, Wyoming, USA", lat: 44.428, lng: -110.5885, difficulty: "medium", added_on: "2026-09-27", notes: "Founded in 1872, it's often called the world's first national park." },
  { name: "Pamukkale, Turkey", lat: 37.9204, lng: 29.1212, difficulty: "medium", added_on: "2026-09-27", notes: "Its white terraces are made of travertine left behind by hot springs." },
  { name: "Lisbon, Portugal", lat: 38.7223, lng: -9.1393, difficulty: "medium", added_on: "2026-09-27", notes: "A huge earthquake in 1755 destroyed much of the city." },
  { name: "Edinburgh, Scotland", lat: 55.9533, lng: -3.1883, difficulty: "medium", added_on: "2026-09-27", notes: "Its castle stands on the plug of an extinct volcano." },
  { name: "Dubrovnik, Croatia", lat: 42.6507, lng: 18.0944, difficulty: "medium", added_on: "2026-09-27", notes: "Medieval walls nearly 2 km long surround its old town." },
  { name: "Stone Town, Zanzibar, Tanzania", lat: -6.1659, lng: 39.2026, difficulty: "medium", added_on: "2026-09-27", notes: "It was a hub of the Indian Ocean spice trade." },
  { name: "Bora Bora, French Polynesia", lat: -16.5004, lng: -151.7415, difficulty: "medium", added_on: "2026-09-27", notes: "A lagoon and barrier reef ring the island's volcanic peaks." },
  { name: "Malé, Maldives", lat: 4.1755, lng: 73.5093, difficulty: "medium", added_on: "2026-09-27", notes: "The Maldives is the world's lowest-lying country, about 1.5 m above sea level on average." },
  { name: "Quebec City, Canada", lat: 46.8139, lng: -71.208, difficulty: "medium", added_on: "2026-09-27", notes: "Its old town has the only surviving city walls in North America north of Mexico." },
  { name: "New Orleans, Louisiana, USA", lat: 29.9511, lng: -90.0715, difficulty: "medium", added_on: "2026-09-27", notes: "Much of the city lies below sea level." },
  { name: "Cartagena, Colombia", lat: 10.391, lng: -75.4794, difficulty: "medium", added_on: "2026-09-27", notes: "Its old town's walls were built to keep out pirates." },
  { name: "Atacama Desert, Chile", lat: -22.9087, lng: -68.1997, difficulty: "medium", added_on: "2026-09-27", notes: "It's one of the driest places on Earth." },
  { name: "Torres del Paine, Chile", lat: -50.9423, lng: -73.4068, difficulty: "medium", added_on: "2026-09-27", notes: "Its granite towers rise above Patagonian glaciers and lakes." },
  { name: "Okavango Delta, Botswana", lat: -19.3, lng: 22.9, difficulty: "medium", added_on: "2026-09-27", notes: "Its river floods inland into the Kalahari instead of reaching the sea." },
  { name: "Zhangjiajie, China", lat: 29.3249, lng: 110.4343, difficulty: "medium", added_on: "2026-09-27", notes: "Its sandstone pillars inspired the floating mountains in the film Avatar." },
  { name: "Ubud, Bali, Indonesia", lat: -8.5069, lng: 115.2625, difficulty: "medium", added_on: "2026-09-27", notes: "Bali's rice terraces are watered by subak, an irrigation system over a thousand years old." },
  { name: "Milford Sound, New Zealand", lat: -44.6414, lng: 167.8974, difficulty: "medium", added_on: "2026-09-27", notes: "It's one of the wettest inhabited places on Earth." },
  { name: "Pompeii, Italy", lat: 40.7489, lng: 14.4989, difficulty: "medium", added_on: "2026-09-27", notes: "Mount Vesuvius buried the Roman town in AD 79." },
  // Hard
  { name: "Lhasa, Tibet, China", lat: 29.652, lng: 91.1721, difficulty: "hard", added_on: "2026-09-27", notes: "At about 3,650 m, it's one of the world's highest cities, with the Potala Palace above it." },
  { name: "Tórshavn, Faroe Islands", lat: 62.0079, lng: -6.79, difficulty: "hard", added_on: "2026-09-27", notes: "One of the world's smallest capitals, where a parliament has met since Viking times." },
  { name: "Pitcairn Islands", lat: -25.066, lng: -130.1015, difficulty: "hard", added_on: "2026-09-27", notes: "About 40 people live here, many descended from the Bounty mutineers." },
  { name: "Kerguelen Islands", lat: -49.35, lng: 70.2167, difficulty: "hard", added_on: "2026-09-27", notes: "Among the most isolated places on Earth, they're also called the Desolation Islands." },
  { name: "Norilsk, Russia", lat: 69.3558, lng: 88.1893, difficulty: "hard", added_on: "2026-09-27", notes: "One of the world's northernmost cities, with no road to the rest of Russia." },
  { name: "Oymyakon, Russia", lat: 63.4608, lng: 142.7858, difficulty: "hard", added_on: "2026-09-27", notes: "Often called the coldest place where people live all year, it has recorded about −68 °C." },
  { name: "Funafuti, Tuvalu", lat: -8.5211, lng: 179.1983, difficulty: "hard", added_on: "2026-09-27", notes: "Tuvalu is one of the world's smallest countries, with about 11,000 people." },
  { name: "Nauru", lat: -0.5228, lng: 166.9315, difficulty: "hard", added_on: "2026-09-27", notes: "One of the world's smallest countries, at about 21 km²." },
  { name: "Alice Springs, Australia", lat: -23.698, lng: 133.8807, difficulty: "hard", added_on: "2026-09-27", notes: "This outback town is close to the middle of Australia." },
  { name: "Kiruna, Sweden", lat: 67.8558, lng: 20.2253, difficulty: "hard", added_on: "2026-09-27", notes: "The town is being moved about 3 km to make room for the iron ore mine under it." },
  { name: "Iqaluit, Nunavut, Canada", lat: 63.7467, lng: -68.517, difficulty: "hard", added_on: "2026-09-27", notes: "It's the capital of Nunavut, Canada's newest territory, created in 1999." },
  { name: "Leh, Ladakh, India", lat: 34.1526, lng: 77.5771, difficulty: "hard", added_on: "2026-09-27", notes: "At about 3,500 m, this Himalayan town is reached by some of the world's highest roads." },
  { name: "Great Blue Hole, Belize", lat: 17.3157, lng: -87.5346, difficulty: "hard", added_on: "2026-09-27", notes: "This sinkhole in the reef is about 300 m across and more than 120 m deep." },
  { name: "Danakil Depression, Ethiopia", lat: 14.2417, lng: 40.3, difficulty: "hard", added_on: "2026-09-27", notes: "One of the hottest places on Earth, with acid pools and salt flats below sea level." },
  { name: "Moynaq, Uzbekistan", lat: 43.7683, lng: 59.0214, difficulty: "hard", added_on: "2026-09-27", notes: "Once a fishing port on the Aral Sea, it now sits in desert far from the shrunken shore." },
  { name: "Darvaza Gas Crater, Turkmenistan", lat: 40.2525, lng: 58.4397, difficulty: "hard", added_on: "2026-09-27", notes: "Nicknamed the Door to Hell, this crater has been burning since it was set alight in 1971." },
  { name: "Mount Roraima, Venezuela/Brazil/Guyana", lat: 5.1433, lng: -60.7625, difficulty: "hard", added_on: "2026-09-27", notes: "Venezuela, Brazil and Guyana meet on its flat top." },
  { name: "Angel Falls, Venezuela", lat: 5.9701, lng: -62.5362, difficulty: "hard", added_on: "2026-09-27", notes: "At 979 m, it's the world's tallest waterfall with an unbroken drop." },
  { name: "Jamestown, Saint Helena", lat: -15.9244, lng: -5.7181, difficulty: "hard", added_on: "2026-09-27", notes: "Napoleon was exiled to this island and died here in 1821." },
  { name: "Tiger's Nest, Bhutan", lat: 27.4919, lng: 89.3632, difficulty: "hard", added_on: "2026-09-27", notes: "This monastery clings to a cliff about 900 m above the Paro valley." },
  { name: "Mount Yasur, Tanna, Vanuatu", lat: -19.532, lng: 169.447, difficulty: "hard", added_on: "2026-09-27", notes: "This volcano has been erupting almost non-stop for centuries." },
  { name: "Lake Assal, Djibouti", lat: 11.6583, lng: 42.4167, difficulty: "hard", added_on: "2026-09-27", notes: "About 155 m below sea level, it's the lowest point in Africa." },
  { name: "Churchill, Manitoba, Canada", lat: 58.7684, lng: -94.165, difficulty: "hard", added_on: "2026-09-27", notes: "It's known as the polar bear capital of the world." },
  { name: "Deception Island, Antarctica", lat: -62.9667, lng: -60.65, difficulty: "hard", added_on: "2026-09-27", notes: "Ships sail right into the flooded crater of this active volcano." },
  { name: "Utqiaġvik, Alaska, USA", lat: 71.2906, lng: -156.7887, difficulty: "hard", added_on: "2026-09-27", notes: "In the northernmost town in the US, the sun doesn't set for more than 80 days in summer." },
  { name: "Avenue of the Baobabs, Madagascar", lat: -20.2507, lng: 44.4186, difficulty: "hard", added_on: "2026-09-27", notes: "Giant baobab trees, some hundreds of years old, line this dirt road." },
  { name: "Chocolate Hills, Bohol, Philippines", lat: 9.8297, lng: 124.1398, difficulty: "hard", added_on: "2026-09-27", notes: "More than 1,200 grassy mounds here turn brown in the dry season." },
];
