// Places for photo practice. Chosen for how recognisable the photo is:
// easy = famous at a glance, medium = well-known sights, hard = striking but
// less famous. photo is the Wikipedia article whose main photo is shown.
// (The database table photo_places holds the same places, and more you add.)
export const PHOTO_PLACES = [
  // Easy
  { name: "Eiffel Tower, Paris, France", lat: 48.8584, lng: 2.2945, difficulty: "easy", photo: "Eiffel Tower", notes: "Built for the 1889 World's Fair, it was only meant to stand for 20 years." },
  { name: "Statue of Liberty, New York, USA", lat: 40.6892, lng: -74.0445, difficulty: "easy", photo: "Statue of Liberty", notes: "A gift from France, dedicated in 1886. Its copper skin is thinner than 2.5 mm." },
  { name: "Big Ben, London, UK", lat: 51.5007, lng: -0.1246, difficulty: "easy", photo: "Big Ben", notes: "Big Ben is the great bell, not the tower, which has been called Elizabeth Tower since 2012." },
  { name: "Sydney Opera House, Australia", lat: -33.8568, lng: 151.2153, difficulty: "easy", photo: "Sydney Opera House", notes: "Its roof sails are covered in over a million tiles made in Sweden." },
  { name: "Taj Mahal, Agra, India", lat: 27.1751, lng: 78.0421, difficulty: "easy", photo: "Taj Mahal", notes: "Shah Jahan built it as a tomb for his wife Mumtaz Mahal. Work began in 1632." },
  { name: "Colosseum, Rome, Italy", lat: 41.8902, lng: 12.4922, difficulty: "easy", photo: "Colosseum", notes: "It could seat an estimated 50,000 to 80,000 spectators." },
  { name: "Golden Gate Bridge, San Francisco, USA", lat: 37.8199, lng: -122.4783, difficulty: "easy", photo: "Golden Gate Bridge", notes: "Its colour, International Orange, was chosen to stand out in the fog." },
  { name: "Christ the Redeemer, Rio de Janeiro, Brazil", lat: -22.9519, lng: -43.2105, difficulty: "easy", photo: "Christ the Redeemer (statue)", notes: "Finished in 1931, the statue is 30 m tall, not counting its pedestal." },
  { name: "Leaning Tower of Pisa, Italy", lat: 43.723, lng: 10.3966, difficulty: "easy", photo: "Leaning Tower of Pisa", notes: "It started to lean in the 1170s, while it was still being built, because the ground is soft." },
  { name: "Great Pyramid of Giza, Egypt", lat: 29.9792, lng: 31.1342, difficulty: "easy", photo: "Great Pyramid of Giza", notes: "It was the tallest human-made structure on Earth for more than 3,800 years." },
  { name: "Tower Bridge, London, UK", lat: 51.5055, lng: -0.0754, difficulty: "easy", photo: "Tower Bridge", notes: "Opened in 1894, its roadway lifts to let tall ships pass underneath." },
  { name: "Burj Khalifa, Dubai, UAE", lat: 25.1972, lng: 55.2744, difficulty: "easy", photo: "Burj Khalifa", notes: "At 828 m, it has been the world's tallest building since 2010." },
  { name: "Mount Rushmore, South Dakota, USA", lat: 43.8791, lng: -103.4591, difficulty: "easy", photo: "Mount Rushmore", notes: "Each of the four presidents' faces is about 18 m tall." },
  { name: "Arc de Triomphe, Paris, France", lat: 48.8738, lng: 2.295, difficulty: "easy", photo: "Arc de Triomphe", notes: "Napoleon ordered it in 1806, but it wasn't finished until 1836." },
  { name: "Saint Basil's Cathedral, Moscow, Russia", lat: 55.7525, lng: 37.6231, difficulty: "easy", photo: "Saint Basil's Cathedral", notes: "Built in the 1550s for Ivan the Terrible, it stands at the end of Red Square." },
  { name: "Machu Picchu, Peru", lat: -13.1631, lng: -72.545, difficulty: "easy", photo: "Machu Picchu", notes: "The Inca built this citadel in the 15th century, about 2,430 m above sea level." },
  { name: "Empire State Building, New York, USA", lat: 40.7484, lng: -73.9857, difficulty: "easy", photo: "Empire State Building", notes: "Built in just over a year and finished in 1931, it was the world's tallest building for nearly 40 years." },
  { name: "Hollywood Sign, Los Angeles, USA", lat: 34.1341, lng: -118.3215, difficulty: "easy", photo: "Hollywood Sign", notes: "It first read \"Hollywoodland\", an advert for a housing development in 1923." },
  { name: "Sagrada Família, Barcelona, Spain", lat: 41.4036, lng: 2.1744, difficulty: "easy", photo: "Sagrada Família", notes: "Gaudí's basilica has been under construction since 1882." },
  { name: "Brandenburg Gate, Berlin, Germany", lat: 52.5163, lng: 13.3777, difficulty: "easy", photo: "Brandenburg Gate", notes: "Built in the 1790s, it stood right by the Berlin Wall from 1961 to 1989." },
  { name: "Space Needle, Seattle, USA", lat: 47.6205, lng: -122.3493, difficulty: "easy", photo: "Space Needle", notes: "It was built for the 1962 World's Fair." },
  { name: "Parthenon, Athens, Greece", lat: 37.9715, lng: 23.7267, difficulty: "easy", photo: "Parthenon", notes: "This temple to Athena was finished in the 5th century BC." },
  { name: "Stonehenge, England", lat: 51.1789, lng: -1.8262, difficulty: "easy", photo: "Stonehenge", notes: "Its smaller bluestones were brought from the Preseli Hills in Wales, more than 200 km away." },
  { name: "Niagara Falls, Canada/USA", lat: 43.0896, lng: -79.0849, difficulty: "easy", photo: "Niagara Falls", notes: "Horseshoe Falls, on the Canadian side, carries about 90% of the river's water." },
  { name: "Petronas Towers, Kuala Lumpur, Malaysia", lat: 3.1579, lng: 101.7116, difficulty: "easy", photo: "Petronas Towers", notes: "They were the world's tallest buildings from 1998 to 2004." },
  { name: "Mount Fuji, Japan", lat: 35.3606, lng: 138.7274, difficulty: "easy", photo: "Mount Fuji", notes: "Japan's highest peak, at 3,776 m. It last erupted in 1707." },
  { name: "Tokyo Tower, Japan", lat: 35.6586, lng: 139.7454, difficulty: "easy", photo: "Tokyo Tower", notes: "Inspired by the Eiffel Tower, it's painted white and orange for air safety." },
  { name: "Neuschwanstein Castle, Germany", lat: 47.5576, lng: 10.7498, difficulty: "easy", photo: "Neuschwanstein Castle", notes: "This 19th-century castle inspired Disney's Sleeping Beauty castle." },
  { name: "Grand Canyon, Arizona, USA", lat: 36.1069, lng: -112.1129, difficulty: "easy", photo: "Grand Canyon", notes: "The Colorado River carved it up to 1.8 km deep." },
  { name: "Angkor Wat, Cambodia", lat: 13.4125, lng: 103.867, difficulty: "easy", photo: "Angkor Wat", notes: "The world's largest religious monument, and it's on Cambodia's flag." },
  { name: "CN Tower, Toronto, Canada", lat: 43.6426, lng: -79.3871, difficulty: "easy", photo: "CN Tower", notes: "It was the world's tallest free-standing structure for more than 30 years." },
  { name: "Marina Bay Sands, Singapore", lat: 1.2834, lng: 103.8607, difficulty: "easy", photo: "Marina Bay Sands", notes: "A 340 m-long SkyPark sits across the tops of its three towers." },
  { name: "Great Wall of China", lat: 40.3587, lng: 116.02, difficulty: "easy", photo: "Great Wall of China", notes: "Its sections together run for more than 20,000 km." },
  // Medium
  { name: "Al-Khazneh, Petra, Jordan", lat: 30.3222, lng: 35.4515, difficulty: "medium", photo: "Al-Khazneh", notes: "The Treasury, carved into Petra's rock face, appears in Indiana Jones and the Last Crusade." },
  { name: "Chichén Itzá, Mexico", lat: 20.6843, lng: -88.5678, difficulty: "medium", photo: "Chichen Itza", notes: "At the equinoxes, shadows make a serpent that seems to slide down El Castillo's steps." },
  { name: "Moai, Easter Island, Chile", lat: -27.1127, lng: -109.3497, difficulty: "medium", photo: "Moai", notes: "The Rapa Nui people carved nearly 1,000 moai statues here." },
  { name: "Hagia Sophia, Istanbul, Turkey", lat: 41.0086, lng: 28.9802, difficulty: "medium", photo: "Hagia Sophia", notes: "Built as a cathedral in 537, it has also been a mosque and a museum." },
  { name: "Alhambra, Granada, Spain", lat: 37.1761, lng: -3.5881, difficulty: "medium", photo: "Alhambra", notes: "A palace and fortress built by the Nasrid rulers of Granada." },
  { name: "Mont-Saint-Michel, France", lat: 48.6361, lng: -1.5115, difficulty: "medium", photo: "Mont-Saint-Michel", notes: "At high tide, the sea can cut this abbey island off from the mainland." },
  { name: "Matterhorn, Switzerland/Italy", lat: 45.9763, lng: 7.6586, difficulty: "medium", photo: "Matterhorn", notes: "The first ascent, in 1865, ended in tragedy: four of the seven climbers died on the way down." },
  { name: "Oia, Santorini, Greece", lat: 36.4618, lng: 25.3753, difficulty: "medium", photo: "Oia, Greece", notes: "Its white houses and blue domes sit on the rim of Santorini's caldera." },
  { name: "Table Mountain, Cape Town, South Africa", lat: -33.9628, lng: 18.4098, difficulty: "medium", photo: "Table Mountain", notes: "Its flat top is about 3 km wide and often covered by a \"tablecloth\" of cloud." },
  { name: "Uluru, Australia", lat: -25.3444, lng: 131.0369, difficulty: "medium", photo: "Uluru", notes: "This sandstone monolith rises about 348 m above the flat desert around it." },
  { name: "Kinkaku-ji, Kyoto, Japan", lat: 35.0394, lng: 135.7292, difficulty: "medium", photo: "Kinkaku-ji", notes: "The Golden Pavilion's top two floors are covered in gold leaf." },
  { name: "Burj Al Arab, Dubai, UAE", lat: 25.1412, lng: 55.1853, difficulty: "medium", photo: "Burj Al Arab", notes: "Shaped like a sail, it stands on its own artificial island." },
  { name: "Sheikh Zayed Grand Mosque, Abu Dhabi, UAE", lat: 24.4128, lng: 54.475, difficulty: "medium", photo: "Sheikh Zayed Grand Mosque", notes: "Its main prayer hall has one of the world's largest hand-knotted carpets." },
  { name: "Charles Bridge, Prague, Czechia", lat: 50.0865, lng: 14.4114, difficulty: "medium", photo: "Charles Bridge", notes: "Begun in 1357, the stone bridge is lined with 30 statues." },
  { name: "Hallgrímskirkja, Reykjavík, Iceland", lat: 64.1417, lng: -21.9266, difficulty: "medium", photo: "Hallgrímskirkja", notes: "Its design was inspired by Iceland's basalt columns." },
  { name: "Potala Palace, Lhasa, Tibet, China", lat: 29.6578, lng: 91.1169, difficulty: "medium", photo: "Potala Palace", notes: "The Dalai Lama's winter palace has more than 1,000 rooms." },
  { name: "Gateway Arch, St. Louis, USA", lat: 38.6247, lng: -90.1848, difficulty: "medium", photo: "Gateway Arch", notes: "At 192 m, it's the world's tallest arch." },
  { name: "Victoria Falls, Zambia/Zimbabwe", lat: -17.9243, lng: 25.8572, difficulty: "medium", photo: "Victoria Falls", notes: "Its local name, Mosi-oa-Tunya, means \"the smoke that thunders\"." },
  { name: "Iguazu Falls, Argentina/Brazil", lat: -25.6953, lng: -54.4367, difficulty: "medium", photo: "Iguazu Falls", notes: "It is a chain of about 275 waterfalls on the border of Argentina and Brazil." },
  { name: "Half Dome, Yosemite, USA", lat: 37.7459, lng: -119.5332, difficulty: "medium", photo: "Half Dome", notes: "Its sheer granite face rises about 1,400 m above Yosemite Valley." },
  { name: "Moraine Lake, Banff, Canada", lat: 51.3217, lng: -116.186, difficulty: "medium", photo: "Moraine Lake", notes: "Its bright blue colour comes from rock flour ground by glaciers." },
  { name: "Plitvice Lakes, Croatia", lat: 44.8654, lng: 15.582, difficulty: "medium", photo: "Plitvice Lakes National Park", notes: "Sixteen terraced lakes are linked by waterfalls." },
  { name: "Cliffs of Moher, Ireland", lat: 52.9715, lng: -9.4309, difficulty: "medium", photo: "Cliffs of Moher", notes: "They rise up to 214 m above the Atlantic." },
  { name: "Edinburgh Castle, Scotland", lat: 55.9486, lng: -3.1999, difficulty: "medium", photo: "Edinburgh Castle", notes: "It stands on the plug of an extinct volcano." },
  { name: "Wat Arun, Bangkok, Thailand", lat: 13.7437, lng: 100.4889, difficulty: "medium", photo: "Wat Arun", notes: "The Temple of Dawn's spires are decorated with pieces of Chinese porcelain." },
  { name: "Borobudur, Java, Indonesia", lat: -7.6079, lng: 110.2038, difficulty: "medium", photo: "Borobudur", notes: "The world's largest Buddhist temple was built in the 9th century." },
  { name: "Shwedagon Pagoda, Yangon, Myanmar", lat: 16.7983, lng: 96.1497, difficulty: "medium", photo: "Shwedagon Pagoda", notes: "Its golden stupa is covered in gold plates and topped with thousands of diamonds." },
  { name: "Ha Long Bay, Vietnam", lat: 20.9101, lng: 107.1839, difficulty: "medium", photo: "Ha Long Bay", notes: "About 1,600 limestone islands and islets rise out of its water." },
  { name: "Meteora, Greece", lat: 39.7217, lng: 21.6306, difficulty: "medium", photo: "Meteora", notes: "Its monasteries sit on top of huge rock pillars." },
  { name: "Dubrovnik, Croatia", lat: 42.6507, lng: 18.0944, difficulty: "medium", photo: "Dubrovnik", notes: "Medieval walls nearly 2 km long surround its old town." },
  { name: "Château Frontenac, Quebec City, Canada", lat: 46.8118, lng: -71.2052, difficulty: "medium", photo: "Château Frontenac", notes: "It's often called the most photographed hotel in the world." },
  { name: "Golden Temple, Amritsar, India", lat: 31.62, lng: 74.8765, difficulty: "medium", photo: "Golden Temple", notes: "Sikhism's holiest gurdwara, its kitchen serves free meals to tens of thousands of people a day." },
  { name: "Temple of Heaven, Beijing, China", lat: 39.8822, lng: 116.4066, difficulty: "medium", photo: "Temple of Heaven", notes: "China's emperors came here to pray for good harvests." },
  { name: "Lake Bled, Slovenia", lat: 46.3625, lng: 14.0938, difficulty: "medium", photo: "Lake Bled", notes: "A church stands on the lake's tiny island, reached by rowing boat." },
  { name: "Hallstatt, Austria", lat: 47.5622, lng: 13.6493, difficulty: "medium", photo: "Hallstatt", notes: "Salt has been mined here for thousands of years." },
  { name: "Grand Canal, Venice, Italy", lat: 45.438, lng: 12.3358, difficulty: "medium", photo: "Grand Canal (Venice)", notes: "Venice's main waterway is crossed by just four bridges." },
  { name: "Pamukkale, Turkey", lat: 37.9204, lng: 29.1212, difficulty: "medium", photo: "Pamukkale", notes: "Its white terraces are made of travertine left behind by hot springs." },
  { name: "Cologne Cathedral, Germany", lat: 50.9413, lng: 6.9583, difficulty: "medium", photo: "Cologne Cathedral", notes: "It took more than 600 years to finish, from 1248 to 1880." },
  { name: "Florence Cathedral, Italy", lat: 43.7731, lng: 11.256, difficulty: "medium", photo: "Florence Cathedral", notes: "Brunelleschi's dome, finished in 1436, is still the largest brick dome ever built." },
  { name: "Atomium, Brussels, Belgium", lat: 50.8949, lng: 4.3415, difficulty: "medium", photo: "Atomium", notes: "Built for the 1958 World's Fair, it models an iron crystal magnified 165 billion times." },
  { name: "Tian Tan Buddha, Hong Kong", lat: 22.254, lng: 113.905, difficulty: "medium", photo: "Tian Tan Buddha", notes: "This 34 m bronze Buddha sits on Lantau Island." },
  // Hard
  { name: "Bagan, Myanmar", lat: 21.1717, lng: 94.8585, difficulty: "hard", photo: "Bagan", notes: "More than 2,000 Buddhist temples and pagodas still stand on its plain." },
  { name: "Salar de Uyuni, Bolivia", lat: -20.1338, lng: -67.4891, difficulty: "hard", photo: "Salar de Uyuni", notes: "After rain, the world's largest salt flat becomes a giant mirror." },
  { name: "Church of Saint George, Lalibela, Ethiopia", lat: 12.0317, lng: 39.0473, difficulty: "hard", photo: "Church of Saint George, Lalibela", notes: "Like Lalibela's other medieval churches, it was carved downwards out of solid rock." },
  { name: "Registan, Samarkand, Uzbekistan", lat: 39.6547, lng: 66.9758, difficulty: "hard", photo: "Registan", notes: "Three madrasas covered in tiles frame this Silk Road square." },
  { name: "Paro Taktsang, Bhutan", lat: 27.4919, lng: 89.3632, difficulty: "hard", photo: "Paro Taktsang", notes: "The Tiger's Nest monastery clings to a cliff about 900 m above the Paro valley." },
  { name: "Djinguereber Mosque, Timbuktu, Mali", lat: 16.7758, lng: -3.0106, difficulty: "hard", photo: "Djinguereber Mosque", notes: "Built of mud in 1327, it helped make Timbuktu a great centre of learning." },
  { name: "Great Mosque of Djenné, Mali", lat: 13.9053, lng: -4.5553, difficulty: "hard", photo: "Great Mosque of Djenné", notes: "The largest mud-brick building in the world, it's re-plastered by the town every year." },
  { name: "Deadvlei, Namibia", lat: -24.7593, lng: 15.2924, difficulty: "hard", photo: "Deadvlei", notes: "Dead camel thorn trees, centuries old, stand on a white clay pan among red dunes." },
  { name: "Avenue of the Baobabs, Madagascar", lat: -20.2507, lng: 44.4186, difficulty: "hard", photo: "Avenue of the Baobabs", notes: "Giant baobab trees, some hundreds of years old, line this dirt road." },
  { name: "Dragon's blood trees, Socotra, Yemen", lat: 12.4634, lng: 53.8237, difficulty: "hard", photo: "Dracaena cinnabari", notes: "These umbrella-shaped trees grow nowhere else in the world." },
  { name: "Chocolate Hills, Bohol, Philippines", lat: 9.8297, lng: 124.1398, difficulty: "hard", photo: "Chocolate Hills", notes: "More than 1,200 grassy mounds here turn brown in the dry season." },
  { name: "Darvaza Gas Crater, Turkmenistan", lat: 40.2525, lng: 58.4397, difficulty: "hard", photo: "Darvaza gas crater", notes: "Nicknamed the Door to Hell, this crater has been burning since it was set alight in 1971." },
  { name: "Mount Roraima, Venezuela/Brazil/Guyana", lat: 5.1433, lng: -60.7625, difficulty: "hard", photo: "Mount Roraima", notes: "Venezuela, Brazil and Guyana meet on its flat top." },
  { name: "Angel Falls, Venezuela", lat: 5.9701, lng: -62.5362, difficulty: "hard", photo: "Angel Falls", notes: "At 979 m, it's the world's tallest waterfall with an unbroken drop." },
  { name: "Sigiriya, Sri Lanka", lat: 7.957, lng: 80.7603, difficulty: "hard", photo: "Sigiriya", notes: "A 5th-century king built his palace on top of this rock, about 180 m high." },
  { name: "Wadi Rum, Jordan", lat: 29.5759, lng: 35.42, difficulty: "hard", photo: "Wadi Rum", notes: "This red desert valley has stood in for Mars in several films." },
  { name: "Göbekli Tepe, Turkey", lat: 37.2231, lng: 38.9225, difficulty: "hard", photo: "Göbekli Tepe", notes: "Its carved stone pillars were raised about 11,000 years ago, before farming began." },
  { name: "Svalbard Global Seed Vault, Norway", lat: 78.2382, lng: 15.4913, difficulty: "hard", photo: "Svalbard Global Seed Vault", notes: "It keeps backup copies of seeds from almost every country." },
  { name: "Kaieteur Falls, Guyana", lat: 5.1753, lng: -59.4803, difficulty: "hard", photo: "Kaieteur Falls", notes: "It has a single drop of 226 m and is one of the world's most powerful waterfalls." },
  { name: "Ellora Caves, India", lat: 20.0258, lng: 75.178, difficulty: "hard", photo: "Ellora Caves", notes: "Its Kailasa temple was carved downwards out of a single rock." },
  { name: "Hampi, India", lat: 15.335, lng: 76.46, difficulty: "hard", photo: "Hampi", notes: "These are the ruins of Vijayanagara, one of the world's largest cities around 1500." },
  { name: "Mount Bromo, Java, Indonesia", lat: -7.9425, lng: 112.953, difficulty: "hard", photo: "Mount Bromo", notes: "This active volcano rises from a vast sea of volcanic sand." },
  { name: "Tsingy de Bemaraha, Madagascar", lat: -18.6667, lng: 44.7167, difficulty: "hard", photo: "Tsingy de Bemaraha National Park", notes: "Its forest of razor-sharp limestone pinnacles is almost impossible to cross." },
  { name: "Fish River Canyon, Namibia", lat: -27.59, lng: 17.61, difficulty: "hard", photo: "Fish River Canyon", notes: "One of the largest canyons in the world, it's about 160 km long." },
  { name: "Trolltunga, Norway", lat: 60.1242, lng: 6.74, difficulty: "hard", photo: "Trolltunga", notes: "This rock ledge juts out about 700 m above a lake." },
  { name: "Ushuaia, Argentina", lat: -54.8019, lng: -68.303, difficulty: "hard", photo: "Ushuaia", notes: "It is often called the southernmost city in the world." },
  { name: "Nuuk, Greenland", lat: 64.1814, lng: -51.6941, difficulty: "hard", photo: "Nuuk", notes: "Greenland's capital was founded in 1728 and is one of the smallest capitals in the world." },
  { name: "Longyearbyen, Svalbard, Norway", lat: 78.2232, lng: 15.6267, difficulty: "hard", photo: "Longyearbyen", notes: "The Svalbard Global Seed Vault is here, holding seeds from around the world." },
];
